### ISSUE TITLE
atrules: true not working with gulp-pixrem

### ISSUE THREAD

**Issue by robzor** [robwierzbowski/node-pixrem#21]
Hi there, 

I'm using gulp-pixrem (latest version) with the atrules: true command but in the compiled css it doesn't seem to be working. Everything was working before with pixrem 0.1.4. Not sure if this is a problem with the gulp implementation or with pixrem itself as I'm a bit of a novice here.

Example code:
```
// Compile the sass + autoprefix + pixrem + livereload
gulp.task('sass', function() {
  return gulp.src(paths.sass)
    .pipe(plumber())
    .pipe(sass({ style: 'expanded' }))
    .pipe(autoprefixer('> 1%', 'last 2 versions', 'Firefox ESR', 'ie 7', 'ie 8', 'ie 9', 'Opera 12.1', 'Android 4'))
    .pipe(pixrem({ atrules: true }))
    .pipe(gulp.dest('public_html/assets/build/site_css/'))
    .pipe(livereload());
});
```

Any ideas?

Thanks,

Rob

**Comment by iamvdo** [comment]
Pixrem takes an object as the second argument, not first one.
You may use:

```javascript
.pipe(pixrem('16px', { atrules: true }))
```

Does it resolve your problem ?

**Comment by jacksleight** [comment]
I was having the same problem and can confirm this worked for me. I'm using this code as I don't want to specify the font size (as it gets read from the CSS):

```
pixrem(undefined, {replace: false, atrules: true, html: true})
```

**Comment by iamvdo** [comment]
Thanks @jacksleight.
