### ISSUE TITLE
Node installation fails

### ISSUE THREAD

**Issue by cibulka** [robwierzbowski/node-pixrem#29]
Hi! 

There are some problems with `pixrem` installation with Node probably related to some Node bug. However some users (including me) encountered the issue while using `pixrem`. So in case you have any idea what could that be, the discussion is here: https://github.com/npm/npm/issues/7349#issuecomment-77565722

Thanks for your work!

**Comment by iamvdo** [comment]
Closing as the problem can't be reproduced. Reopen if still in trouble.
