### ISSUE TITLE
Handle input source map

### ISSUE THREAD

**Issue by OliverJAsh** [robwierzbowski/node-pixrem#30]
If a file has a source map annotation, Pixrem removes it. Pixrem should handle the input source map.

**Comment by iamvdo** [comment]
Not pixrem, it's how postcss works. What's your workflow/use case ?

**Comment by OliverJAsh** [comment]
The latest version of PostCSS will read the source map of the input file (from the annotation), update it along with the CSS, and then export a new source map.

**Comment by iamvdo** [comment]
OK, so you have to pass sourcemaps option to pixrem. By default sourcemaps are disabled.
```javascript
var processed = pixrem.process(css, '16px', {}, {map: {inline: false}, to: 'out.css'});
```
Is this what you want ? (some code will be very helpful)

**Comment by mrwweb** [comment]
Is there an equivalent way to pass those arguments to grunt-pixrem? I think I'm hitting the same issue with that.

**Comment by iamvdo** [comment]
@mrwweb grunt-pixrem is deprecated. Consider using grunt-postcss. And yes, you can pass options: https://github.com/nDmitry/grunt-postcss#usage
