### ISSUE TITLE
Changing font-size based on media queries

### ISSUE THREAD

**Issue by jsheffers** [robwierzbowski/node-pixrem#32]
I'm using mobile first media queries to increase the body font size on larger devices.  It seems that this plugin won't allow for that kind of functionality.  Here are a few examples I've tried.

```
.pipe($.pixrem('16px', { html: false, atrules: false }))

.pipe($.pixrem('16px', { html: false, atrules: true }))

.pipe($.pixrem('16px', { html: true, atrules: false }))

.pipe($.pixrem('16px', { html: false, atrules: false }))
```

CSS

```
html,body {
  font-size: 14px;
  @include breakpoint(desktop) {
    font-size: 16px;    
  }
}
```

No matter what I do it renders 1rem = 14px.  Is there a way around this?  Considering I only need 1rem = 16px in IE8.  I would prefer to force it to render 16px as 1rem instead of having it read directly from the body, which is what I thought the HTML option was doing...

**Comment by tbredin** [comment]
+1. I've been checking back here now and then to see if it's been updated. I raised this issue here a while ago, see #12. 

Since rem units are tied to the `font-size` set on the `html` element it seems like the plugin could match a change in this value to any rem units sharing the same media query. 

To be honest, do we even need to specify `rootsize` at all? Can't postcss read the font size from the `html` element at any media query, and do it's thing?

**Comment by tbredin** [comment]
The issue as I see it is really that any `rem` fallback should read the `html` `font-size`; that's how `rem` units work.

This plugin doesn't, so isn't really useful unless you never touch that value.

**Comment by davetgreen** [comment]
I've just noticed that pixrem isn't implementing fallbacks when the font-size is nested within a media query, which is a big issue for us. Are there any plans to resolve this in the near future?

**Comment by davetgreen** [comment]
hi @robwierzbowski, it would appear that the pixel fallback that is the core of this module's functionality doesn't work when nested inside media queries.

Is this somehow intentional? Thanks.

**Comment by iamvdo** [comment]
>Is this somehow intentional?

If I'm understand your problem, yes.

Did you try the `atrules` option, that forces fallback in at-rules too (media-queries)?

**Comment by davetgreen** [comment]
@iamvdo I confess, I wasn't even aware of that rule! Just tried now and it resolves the issue, thank you!

**Comment by iamvdo** [comment]
Good to hear!
