### ISSUE TITLE
Use browserlist to handle rem for IE9/10/11 in pseudo element only

### ISSUE THREAD

**Issue by MoOx** [robwierzbowski/node-pixrem#36]
What do you think about handling this issue directly in this plugin using [browserslist](https://github.com/ai/browserslist) ?

> IE 9, 10 and 11 do not support rem units when used in the "line-height" property when used on :before and :after pseudo elements (https://connect.microsoft.com/IE/feedback/details/776744).

That would be a great step to avoid most px fallbacks when you don't need to support IE8.

**Comment by iamvdo** [comment]
Well, does it worth it?
As far as I understand, you want rem fallbacks for IE9,10 and 11 for `line-height`, only if it's a pseudo-element ?

Because this module already avoid most px fallbacks... [Not based on browserlist though](https://github.com/robwierzbowski/node-pixrem/issues/5)

**Comment by MoOx** [comment]
It's seems to be more than that http://caniuse.com/#search=rem

> IE 9 & IE 10 do not support rem units when used in the font shorthand property (the entire declaration is ignored) or when used on pseudo elements.

I know it's not based on browserlist. But the idea is to use browserlist to know what people are scoping in order to adjust automatically the behavior of this plugin.
Or you can just enable that with an option but it will be not bring a cool ux :)

**Comment by iamvdo** [comment]
I'm not sure to understand, but basically, we need to provide a px fallback for IE9,10:
  * for the `font` shorthand declaration
  * for all declarations in pseudo-elements (only line-height for IE11)
  * based on browserlist

I still don't get why:

>That would be a great step to avoid most px fallbacks when you don't need to support IE8.

**Comment by MoOx** [comment]
If you rely on browserslist to detect the current browser scope to adjust where to enable the px fallback, that would be enough:

- most fallback for ie8 (current behavior)
- only fallbacks for ie9/10/11 like you listed above.

Maybe you can disable all fallback if browser scope is > ie 11 (or if there is no ie involved).

**Comment by iamvdo** [comment]
Can you test this PR #37 and give feedback ?
Is it what you have in mind ?

**Comment by MoOx** [comment]
Yep !

**Comment by iamvdo** [comment]
Fixed in @1.3.0
