### ISSUE TITLE
Returns PC as default unit

### ISSUE THREAD

**Issue by fraincs** [robwierzbowski/node-pixrem#42]
Strangely the fallback returned is 16pc et not 16px

**Comment by iamvdo** [comment]
What do you mean? Give us an example

**Comment by eltonmesquita** [comment]
I'm having this same issue when using with the postcss grunt plugin. 
Using like thin:
`options: {
        map: true, // inline sourcemaps

        processors: [
          require('pixrem')(), // add fallbacks for rem units
          require('autoprefixer-core')({browsers: 'last 4 versions'}), // add vendor prefixes
          require('cssnano')() // minify the result
        ]
      },`

and getting this as result:
`.my-class {
    min-height: 9pc;
    min-height: 9rem;
    padding-bottom: 1pc;
    padding-bottom: 1rem;
}
``
If you need more details, just ask ;D

**Comment by iamvdo** [comment]
It's not a pixrem issue. It seems that it is from cssnano, from `postcss-convert-values`'s `convert.js` file. Open issue there: https://github.com/ben-eb/postcss-convert-values/issues/11
