### ISSUE TITLE
'Root font-size is invalid' Error does not contain .source

### ISSUE THREAD

**Issue by TrevorPT** [robwierzbowski/node-pixrem#46]
Hello,

I'm using pixrem with bluebird promises to process a series of .css files.  I want to use the root font-size from the .css file but I hit one file that does not have the font-size set on the `html` node and pixrem is throwing an error: `Root font-size is invalid`.  Unlike a CssSyntaxError, the Error object does not include the source so I cannot tell which source caused the error.  When pixrem throws a CssSyntaxError, it includes a `.source` property so that I can just return the original source css up the bluebird chain via `.catch`.

```javascript
.then( function ( cssBuffer ) {
    var css = PostCSSPixrem.process( cssBuffer, null, { atrules: true } );
    return css; // returns a string
} )
.catch( function ( error ) {
    // catch PostCSS parsing errors
    if ( error.name === 'CssSyntaxError' ) {
        // Just return the original source css
        return error.source;
    }
    // catch any file errors, like a missing file
    if ( error.fileName ) {
        return null;
    }
    // else an unexpected error
    // Try to return the original source css if available
    return error.source;
} )
```
Can pixrem include the source in the thrown Error or is there a better way for me to do this?

Thanks, and thanks for a useful library.

**Comment by TrevorPT** [comment]
I figured out two workarounds:

1. use `PostCSSPixrem.process( cssBuffer, '16px', { atrules: true } );` -- after I reread the documentation for the nth time, I saw  "*Pixrem also tries to get the root font-size from CSS (html or :root) and* **overrides this option**."  Initially I had assumed this option would override the root font-size, so I had it backwards.

2. use try/catch around `.process` instead of using .catch -- this way I can localize the exception catching to pixrem and return the source css
```javascript
.then( function ( css ) {
    try {
        var cssResult = PostCSSPixrem.process( css, '16px', { atrules: true } );
        return cssResult; // returns a string
    }
    catch ( error ) {
        return css; // return the original source
    }
} )
```

You can close this issue if you don't think having `.source` is useful in the thrown Error.

Thanks.

**Comment by iamvdo** [comment]
It will be useful, yes, but pixrem should be rewritten (following PostCSS plugin guidelines) and it's not planned for now.
I'll keep this open.

**Comment by TrevorPT** [comment]
Okay, thanks anyways for the response and for the library -- even in its current form it's still very useful.
