### ISSUE TITLE
Setting height: 10rem returns 75pt?

### ISSUE THREAD

**Issue by zalgocykel** [robwierzbowski/node-pixrem#52]
Hello,

Just starting trying this for a new project. I did notice something strange, for an element i wrote
`height: 10rem` and got `height: 75pt; height: 10rem;`
same thing using margin with 10rem
`   margin: 75pt 0 35px;
    margin: 10rem 0 3.5rem;
`

Why would I even get pt?

**Comment by iamvdo** [comment]
Not a pixrem problem. Are you using cssnano ?
