### ISSUE TITLE
pixrem: Unit cannot be used for conversion, so 16px is used.

### ISSUE THREAD

**Issue by Bin4ryIO** [robwierzbowski/node-pixrem#60]
How do I silent this warning? I'm currently using Gatsby and find no where to disable this warning. I get that is not possible to calculate rem before vp rendering.

Thanks in advance.

**Comment by iamvdo** [comment]
`pixrem` does not print this message. It just adds a warning to postcss `Result` instance. Which runner are you using?

**Comment by nodox** [comment]
Still looking for a solution to this problem

**Comment by dotnetCarpenter** [comment]
@iamvdo I got the same issue. I'm using [postcss-loader](https://github.com/postcss/postcss-loader) which runs [postcss-cssnext](https://github.com/MoOx/postcss-cssnext) which in turn runs *pixrem*. Do you know how to silent only the pixrem warning about the 16px default?

In my use case, I have the root font-size, set to either a percentage value or view width but the 16px default is perfect as fallback. Unfortunately, the warning output is useless, With so many warnings that I don't care about, I won't notice if there is warning that I actually care about.

**Comment by iamvdo** [comment]
@nodox @dotnetCarpenter You should use something like https://github.com/postcss/postcss-reporter to blacklist messages from a specific plugin

**Comment by Kentoss** [comment]
@dotnetCarpenter I am doing the exact same thing and running into the exact same issue. After a documentation dive, I have found you can disable the use of pixrem with the following configuration using postcss-loader:

postcss.config.js
```js
module.exports = {
  plugins: {
    'postcss-cssnext': {
      features: {
       rem: false
      }
    }
  }
}
```

This issue is the top result when searching for the error message, so I hope this helps.

**Comment by dotnetCarpenter** [comment]
@Kentoss I dropped cssnext and choose only the postcss plugins I needed. Pixrem was not one of them.
